### ISSUE TITLE
Add refresh toggle option as well?

### ISSUE THREAD

**Issue by please-be-nice** [FrogTheFrog/gsync-toggle#2]
Would you be able to extend this to enable setting 'Max Refresh Rate' in nvcp as well? I discovered I have to turn gsync completely off for the application in order for the stream to be good (setting it only to fullscreen doesn't stop it from destroying the stream), but I also have to fix the refresh rate in nvcp to match the moonlight client. I have fps limit in nvcp set to 163 for all games and gsync/vsync turned on per blurbusters recommendations, it would be nice to be able to use your tool to turn off gsync as well as set refresh rate, then set the settings back to what they were.

**Comment by FrogTheFrog** [comment]
Copying from Sunshine's discord:

To have Sunshine set an FPS limit in NVIDIA Control Panel automatically:

Download frltoggle.exe https://github.com/FrogTheFrog/frl-toggle/releases
Add whatever application you want to stream (Desktop for example) and add this to the Command Preparations section:

For `do` enter `cmd /C <full path>frltoggle.exe %SUNSHINE_CLIENT_FPS% --save-previous-or-reuse`

    it will automatically set to the stream FPS requested in Moonlight.
    instead of `%SUNSHINE_CLIENT_FPS%` you can set any value `1-1023`

For `undo` enter `cmd /C <full path>frltoggle.exe load-file`

    this will set it back to the saved value / your standard setting.
    instead of load-file you can set any value `0-1023` (0 for off)

**Comment by FrogTheFrog** [comment]
gsync tool does not have load/save functionality, but I don't thing it's needed since we only have 3 values anyway...

**Comment by please-be-nice** [comment]
ah ok that makes sense, I didn't know about the other tool. thanks!
