### ISSUE TITLE
Use for Sunshine commands?

### ISSUE THREAD

**Issue by ScraggyMcRaggy** [FrogTheFrog/gsync-toggle#3]
Is it possible to use this in conjunction with Sunshine Command Preps? For example, turn g-sync off on Sunshine app launch, turn g-sync off when Sunshine app closes? This is the exact automation I'm trying to achieve at the moment.

Sorry if this is a stupid question...

**Comment by FrogTheFrog** [comment]
Yes

**Comment by ScraggyMcRaggy** [comment]
> Yes

Good to know. Do you have an example command that would enable g-sync on start up?

**Comment by FrogTheFrog** [comment]
Have you read README?
It's literally like `<path_to_exe>/gsynctoggle.exe 1`.
